config/routes.rb
Rails.application.routes.draw do

  resources :demos, only: [:index]
  namespace :demos do
    resources :datatables, only: [:index]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "demos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/demo.rb
module Demo
  def self.table_name_prefix
    "demo_"
  end
end

app/models/demo/user.rb
class Demo::User < ApplicationRecord
  ROLES = %w[admin member guest].freeze

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def role?(role)
    roles.include?(role.to_s)
  end
end

app/models/demos.rb
module Demos
  def self.table_name_prefix
    "demos_"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/demos/datatables_controller.rb
class Demos::DatatablesController < ApplicationController
  def index
    @users = Demo::User.all
    @users = Demo::User.search(params[:search]) if params[:search].present?
    @pagy, @users = pagy(
      @users.reorder(sort_column => sort_direction),
      items: params.fetch(:count, 10)
    )
  end

  def sort_column
    %w{ name email is_active created_at }.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w{ asc desc }.include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def sort_link_to(name, column, **options)
    if params[:sort] == column.to_s
      direction = params[:direction] == "asc" ? "desc" : "asc"
    else
      direction = "asc"
    end

    link_to name, request.params.merge(sort: column, direction: direction), **options
  end
end

app/helpers/demos/datatables_helper.rb
module Demos::DatatablesHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/datatables/_user.html.erb
<div id="<%= dom_id(user) %>" class="table-row">
  <div class="table-cell pr-4">
    <%= user.name %>
  </div>

  <div class="table-cell pr-4">
    <%= user.email %>
  </div>

  <div class="table-cell pr-4">
    <%= user.is_active? ? "Active" : "Inactive" %>
  </div>

  <div class="table-cell pr-4">
    <%= user.created_at %>
  </div>
</div>

app/views/demos/datatables/index.html.erb
<div class="w-full flex flex-col gap-3">
  <h1 class="font-bold text-4xl">Datatables</h1>

  <%= form_with url: "", method: :get,
                html: { class: "flex flex-col gap-2" },
                data: { turbo_frame: "demo_users", turbo_action: "advance" } do |form| %>

    <div class="relative mb-6">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
        <%= inline_svg_tag "icons/search.svg", aria: { hidden: true }, class: "w-4 h-4 fill-slate-400" %>
      </div>
      <%= form.search_field :query, value: params[:search],
                            class: %w[
                              border rounded-lg block w-full ps-10 p-2.5 bg-slate-700
                              border-slate-600 placeholder-slate-400 text-white
                              focus:ring-blue-500 focus:border-blue-500
                            ].join(" "),
                            placeholder: "Search..." %>
    </div>
  <% end %>


  <%= turbo_frame_tag :demo_users do %>
    <div class="w-full table border border-slate-600 border-collapse">
      <div class="table-header-group">
        <%= sort_link_to "Name", :name, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Email", :position, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Is Active", :office, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Created At", :start_date, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
      </div>
      <%= render partial: "user", collection: @users %>
    </div>
  <% end %>

  <%# TODO: For some reason, pagy_nav renders a String instead of HTML %>
  <%== pagy_nav @pagy %>
</div>

app/views/demos/index.html.erb
<div>
  <h1 class="font-bold text-4xl mb-4">Demos</h1>

  <article class="flex flex-wrap gap-3 bg-slate-100 rounded-md border border-slate-200 p-4">
    <h2 class="font-bold text-2xl">Datatables</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi corporis cum
      dolorum eaque et ex facere illo maiores optio pariatur quas quisquam quo suscipit
      tempore, tenetur velit voluptate voluptates.
    </p>
    <%= link_to "View Demo", demos_datatables_path,
                class: "bg-blue-500 rounded-md px-4 py-2 text-white hover:bg-blue-700" %>
  </article>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-800 text-slate-100">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>